# Simple Fraud Agent Evaluation

This notebook evaluates the simple E2B fraud agent with an AML Investigation-style workflow:
- define a small evaluation dataset
- run the agent case-by-case
- score outputs with deterministic rubric checks
- summarize aggregate performance

In [1]:
%pip install -q aieng-agents python-dotenv pandas langfuse

Note: you may need to restart the kernel to use updated packages.

In [2]:
from pathlib import Path
import asyncio
import json
import statistics

import pandas as pd
from dotenv import load_dotenv
from aieng.agent_evals.async_client_manager import AsyncClientManager
from aieng.agent_evals.langfuse import init_tracing, is_tracing_enabled

load_dotenv()

LANGFUSE_EXPERIMENT_NAME = "fraud-agent-simple-e2b-evaluation"
LANGFUSE_TRACING_ENABLED = init_tracing(service_name=LANGFUSE_EXPERIMENT_NAME)
langfuse_client = AsyncClientManager.get_instance().langfuse_client

NOTEBOOK_CANDIDATES = [
    Path("/home/coder/eval-agents/implementations/cibc-three/Fraud_Agent_Simple_E2B.ipynb"),
    Path("implementations/cibc-three/Fraud_Agent_Simple_E2B.ipynb"),
    Path("Fraud_Agent_Simple_E2B.ipynb"),
]

SOURCE_NOTEBOOK = next((path for path in NOTEBOOK_CANDIDATES if path.exists()), None)
if SOURCE_NOTEBOOK is None:
    tried = [str(path) for path in NOTEBOOK_CANDIDATES]
    raise FileNotFoundError(f"Could not locate source notebook. Tried: {tried}")

print(f"Source notebook: {SOURCE_NOTEBOOK}")
print(f"Langfuse tracing enabled: {LANGFUSE_TRACING_ENABLED and is_tracing_enabled()}")

2026-03-26 16:57:27,297 WARNING opentelemetry.trace: Overriding of current TracerProvider is not allowed
2026-03-26 16:57:32,269 INFO aieng.agent_evals.langfuse: Langfuse tracing initialized successfully (endpoint: https://us.cloud.langfuse.com/api/public/otel)

Source notebook: /home/coder/eval-agents/implementations/cibc-three/Fraud_Agent_Simple_E2B.ipynb
Langfuse tracing enabled: True

## Load the Agent Notebook

This cell executes the source notebook code cells in-process so the evaluation notebook can call `ask_simple_fraud_agent` directly.

In [3]:
def _extract_python_from_notebook(notebook_path: Path) -> str:
    payload = json.loads(notebook_path.read_text())
    code_chunks = []
    for cell in payload.get("cells", []):
        if cell.get("cell_type") != "code":
            continue
        source = cell.get("source", [])
        lines = []
        for line in source:
            if line.lstrip().startswith("%"):
                continue
            lines.append(line)
        if lines:
            code_chunks.append("\n".join(lines))
    return "\n\n".join(code_chunks)


def _strip_top_level_runtime_blocks(code: str) -> str:
    lines = code.splitlines()
    cleaned_lines = []
    skip_block = False
    block_indent = 0

    blocked_prefixes = (
        "simple_session = await simple_session_service.create_session(",
        "response = await ask_simple_fraud_agent(",
    )
    blocked_single_lines = (
        'print(response)',
        'print("Simple fraud agent ready.")',
        'print("Use: await ask_simple_fraud_agent(\'Find suspicious patterns in the database\')")',
    )

    for line in lines:
        stripped = line.lstrip()
        indent = len(line) - len(stripped)

        if skip_block:
            if stripped and indent <= block_indent and not stripped.startswith(")"):
                skip_block = False
            else:
                continue

        if any(stripped.startswith(prefix) for prefix in blocked_prefixes):
            cleaned_lines.append(f"# disabled during eval notebook loading: {stripped}")
            skip_block = True
            block_indent = indent
            continue

        if indent == 0 and stripped in blocked_single_lines:
            cleaned_lines.append(f"# disabled during eval notebook loading: {stripped}")
            continue

        cleaned_lines.append(line)

    return "\n".join(cleaned_lines)


agent_globals = {}
agent_code = _extract_python_from_notebook(SOURCE_NOTEBOOK)
agent_code = _strip_top_level_runtime_blocks(agent_code)

exec(agent_code, agent_globals)

simple_session_service = agent_globals["simple_session_service"]
simple_fraud_agent = agent_globals["simple_fraud_agent"]
simple_session = await simple_session_service.create_session(
    app_name=simple_fraud_agent.name,
    user_id="notebook-user",
    state={},
)
agent_globals["simple_session"] = simple_session

ask_simple_fraud_agent = agent_globals["ask_simple_fraud_agent"]

print("Simple fraud agent loaded for evaluation.")

2026-03-26 16:57:36,092 INFO root: Langfuse host: https://us.cloud.langfuse.com
2026-03-26 16:57:36,100 WARNING opentelemetry.trace: Overriding of current TracerProvider is not allowed
2026-03-26 16:57:36,115 WARNING opentelemetry.trace: Overriding of current TracerProvider is not allowed

Langfuse tracing enabled: fraud-agent-simple-e2b-march25
Simple E2B fraud agent config ready.
Read-only SQL + simple fraud tools ready.
Simple fraud agent loaded for evaluation.

In [4]:
orig_run_readonly_query = agent_globals["run_readonly_query"]

async def debug_run_readonly_query(query, row_limit):
    try:
        return await orig_run_readonly_query(query, row_limit)
    except Exception as exc:
        print("\n--- Rejected Query ---\n", query, "\n----------------------")
        raise

agent_globals["run_readonly_query"] = debug_run_readonly_query
print("Debug wrapper installed for run_readonly_query.")

Debug wrapper installed for run_readonly_query.

## Evaluation Dataset

These cases follow the AML evaluation idea of having structured prompts plus expected signal categories for deterministic checks.

In [5]:
eval_cases = [
    {
        "id": "fraud-001",
        "prompt": (
            "Identify the top 3 highest-risk clients in the database by combining transaction amount "
            "and velocity signals. For each client, state their total transaction value, transaction count, "
            "and a specific reason why the combination of both signals makes them suspicious. "
            "Include at least 2 sample transaction IDs per client. "
            "Rank them explicitly from highest to lowest risk."
        ),
        "expected_signals": ["amount", "velocity", "risk", "recommendations"],
    },
    {
        "id": "fraud-002",
        "prompt": (
            "Find merchants that appear in more than one fraud signal (e.g. both high transaction volume "
            "and broad client/state exposure). For each merchant you identify, name the specific signals "
            "they appear in, provide the supporting counts or amounts, and explain why overlap across "
            "signals increases suspicion compared to a single-signal finding. "
            "Include at least 2 sample transaction IDs per merchant."
        ),
        "expected_signals": ["merchant", "amount", "velocity", "risk", "recommendations"],
    },
    {
        "id": "fraud-003",
        "prompt": (
            "Compare the risk profile of high-velocity clients versus high-amount clients. "
            "Which group poses a higher systemic fraud risk and why? Support your conclusion with "
            "specific counts, amounts, or thresholds drawn from the database — do not make general claims "
            "without citing actual figures. Include sample transaction IDs from each group to justify "
            "the comparison. End with a prioritised list of recommended actions."
        ),
        "expected_signals": ["amount", "velocity", "risk", "recommendations"],
    },
    {
        "id": "fraud-004",
        "prompt": (
            "Write a fraud investigation brief covering all three signals (high-value transactions, "
            "velocity anomalies, and risky merchants). For each signal, identify the single most suspicious "
            "entity (client or merchant), state the specific metric that makes it suspicious (e.g. exact "
            "amount, count, number of states), and include sample transaction IDs tied to each signal. "
            "Cross-reference where the same entity appears in more than one signal. "
            "Conclude with a risk-ranked action plan."
        ),
        "expected_signals": ["amount", "velocity", "merchant", "risk", "recommendations"],
    },
    {
        "id": "fraud-005",
        "prompt": (
            "Which clients or merchants identified as high-risk could plausibly have a legitimate "
            "business explanation for their activity? For each one you name, state the data that "
            "initially flagged them, include sample transaction IDs, describe what a benign explanation "
            "might look like, and explain what additional evidence would be needed to confirm or rule out fraud. "
            "Focus on nuance — do not simply list all flagged entities as suspicious."
        ),
        "expected_signals": ["amount", "velocity", "merchant", "risk", "recommendations"],
    },
]

In [6]:
async def load_fraud_label_ground_truth(limit: int = 10000) -> dict:
    code = f"""
import json
import sqlite3

conn = sqlite3.connect({agent_globals['E2B_SQLITE_PATH']!r})
conn.row_factory = sqlite3.Row

rows = [dict(row) for row in conn.execute(
    "SELECT transaction_id, fraud FROM fraud_labels LIMIT ?",
    ({int(limit)},),
).fetchall()]

payload = {{
    "rows": rows,
}}
print(json.dumps(payload, default=str))
conn.close()
"""
    raw_result = await agent_globals["shared_code_interpreter"].run_code(code=code)
    return json.loads(agent_globals["_extract_stdout_text"](raw_result).strip())


def _is_positive_fraud_label(value) -> bool:
    normalized = str(value).strip().lower()
    return normalized in {"1", "true", "yes", "fraud", "fraudulent", "positive"}


fraud_label_ground_truth = await load_fraud_label_ground_truth()
positive_fraud_transaction_ids = {
    int(row["transaction_id"])
    for row in fraud_label_ground_truth["rows"]
    if row.get("transaction_id") is not None and _is_positive_fraud_label(row.get("fraud"))
}

for case in eval_cases:
    case["ground_truth_positive_transaction_ids"] = sorted(positive_fraud_transaction_ids)
    case["ground_truth_positive_count"] = len(positive_fraud_transaction_ids)

pd.DataFrame(eval_cases)

2026-03-26 16:57:36,211 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 16:57:36,213 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes

2026-03-26 16:57:36,582 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 16:57:36,583 INFO e2b.api: Response 201
2026-03-26 16:57:36,586 INFO e2b.api.client_async: Request: POST https://49999-ihoipe1ecjrolukcmsekf.e2b.app/execute
2026-03-26 16:57:36,711 INFO e2b.api.client_async: Response: 200 https://49999-ihoipe1ecjrolukcmsekf.e2b.app/execute
2026-03-26 16:57:37,167 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/ihoipe1ecjrolukcmsekf
2026-03-26 16:57:37,168 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/ihoipe1ecjrolukcmsekf
2026-03-26 16:57:37,288 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/ihoipe1ecjrolukcmsekf
2026-03-26 16:57:37,290 INFO e2b.api: Response 204

,id,prompt,expected_signals,ground_truth_positive_transaction_ids,ground_truth_positive_count
0,fraud-001,Identify the top 3 highest-risk clients in the...,"[amount, velocity, risk, recommendations]","[7760583, 7803991, 7849591, 7959875, 8049815, ...",14
1,fraud-002,Find merchants that appear in more than one fr...,"[merchant, amount, velocity, risk, recommendat...","[7760583, 7803991, 7849591, 7959875, 8049815, ...",14
2,fraud-003,Compare the risk profile of high-velocity clie...,"[amount, velocity, risk, recommendations]","[7760583, 7803991, 7849591, 7959875, 8049815, ...",14
3,fraud-004,Write a fraud investigation brief covering all...,"[amount, velocity, merchant, risk, recommendat...","[7760583, 7803991, 7849591, 7959875, 8049815, ...",14
4,fraud-005,Which clients or merchants identified as high-...,"[amount, velocity, merchant, risk, recommendat...","[7760583, 7803991, 7849591, 7959875, 8049815, ...",14

## AML-Style Deterministic Graders

These checks are simpler than the AML repo graders, but they follow the same pattern: case-level scoring first, then aggregate run-level metrics.

In [ ]:
import re
import statistics

SECTION_HEADERS = ["ANALYSIS:", "FINDINGS:", "RISK:", "RECOMMENDATIONS:"]
SIGNAL_KEYWORDS = {
    "amount": ["amount", "high-value", "transaction", "outlier"],
    "velocity": ["velocity", "transaction count", "rapid", "frequency", "client"],
    "merchant": ["merchant", "state", "clients", "exposure"],
    "risk": ["risk", "high", "medium", "low", "critical"],
    "recommendations": ["recommend", "review", "monitor", "investigate", "escalate"],
}

# Require at least this many transaction IDs in each response.
MIN_TRANSACTION_IDS_PER_CASE = 3


def score_structure(text: str) -> float:
    return sum(header in text for header in SECTION_HEADERS) / len(SECTION_HEADERS)


def score_expected_signals(text: str, expected_signals: list[str]) -> float:
    lower_text = text.lower()
    hits = 0
    for signal in expected_signals:
        keywords = SIGNAL_KEYWORDS[signal]
        if any(keyword in lower_text for keyword in keywords):
            hits += 1
    return hits / len(expected_signals) if expected_signals else 0.0


def score_evidence_density(text: str) -> float:
    markers = ["transaction", "client", "merchant", "amount", "state"]
    lower_text = text.lower()
    hits = sum(marker in lower_text for marker in markers)
    return min(1.0, hits / 4)


def extract_transaction_ids(text: str) -> set[int]:
    ids: set[int] = set()

    # Capture list-style formats like:
    # "Sample transaction IDs: 7475385, 7475440, 7475633"
    list_matches = re.findall(
        r"(?:sample\s+)?transaction[_\s-]?ids?\s*[:#-]?\s*((?:\d+[\s,;]*(?:and\s+)?)+)",
        text,
        flags=re.IGNORECASE,
    )
    for match in list_matches:
        ids.update(int(m) for m in re.findall(r"\d+", match))

    # Capture single inline formats like:
    # "transaction_id: 12345"
    single_matches = re.findall(
        r"(?:transaction[_\s-]?id\s*[:#-]?\s*)(\d+)",
        text,
        flags=re.IGNORECASE,
    )
    ids.update(int(m) for m in single_matches)

    return ids


def score_transaction_id_coverage(output_text: str, min_ids: int = MIN_TRANSACTION_IDS_PER_CASE) -> float:
    predicted_ids = extract_transaction_ids(output_text)
    if min_ids <= 0:
        return 1.0
    return min(1.0, len(predicted_ids) / min_ids)


def score_ground_truth_alignment(case: dict, output_text: str) -> float:
    predicted_ids = extract_transaction_ids(output_text)
    truth_ids = set(case.get("ground_truth_positive_transaction_ids", []))
    if not truth_ids:
        return 0.0
    if not predicted_ids:
        return 0.0

    true_positives = len(predicted_ids & truth_ids)
    precision = true_positives / len(predicted_ids) if predicted_ids else 0.0
    recall = true_positives / len(truth_ids) if truth_ids else 0.0
    if precision + recall == 0:
        return 0.0
    f1 = (2 * precision * recall) / (precision + recall)
    return min(1.0, round(f1, 3))


def item_level_deterministic_grader(case: dict, output_text: str) -> dict:
    structure_score = score_structure(output_text)
    signals_score = score_expected_signals(output_text, case["expected_signals"])
    evidence_score = score_evidence_density(output_text)
    id_coverage_score = score_transaction_id_coverage(output_text)
    ground_truth_score = score_ground_truth_alignment(case, output_text)

    overall_score = round(
        statistics.mean(
            [structure_score, signals_score, evidence_score, id_coverage_score, ground_truth_score]
        ),
        3,
    )

    predicted_ids = extract_transaction_ids(output_text)

    return {
        "structure_score": round(structure_score, 3),
        "signals_score": round(signals_score, 3),
        "evidence_score": round(evidence_score, 3),
        "id_coverage_score": round(id_coverage_score, 3),
        "predicted_transaction_id_count": len(predicted_ids),
        "min_required_transaction_ids": MIN_TRANSACTION_IDS_PER_CASE,
        "meets_min_transaction_ids": len(predicted_ids) >= MIN_TRANSACTION_IDS_PER_CASE,
        "ground_truth_score": round(ground_truth_score, 3),
        "overall_score": overall_score,
        "pass": overall_score >= 0.7,
    }


def run_level_grader(rows: list[dict]) -> dict:
    overall_scores = [row["overall_score"] for row in rows]
    pass_rate = sum(row["pass"] for row in rows) / len(rows) if rows else 0.0
    ground_truth_scores = [row.get("ground_truth_score", 0.0) for row in rows]
    id_coverage_scores = [row.get("id_coverage_score", 0.0) for row in rows]
    id_requirement_pass_rate = (
        sum(row.get("meets_min_transaction_ids", False) for row in rows) / len(rows)
        if rows
        else 0.0
    )

    return {
        "cases": len(rows),
        "mean_overall_score": round(statistics.mean(overall_scores), 3) if overall_scores else 0.0,
        "min_overall_score": round(min(overall_scores), 3) if overall_scores else 0.0,
        "max_overall_score": round(max(overall_scores), 3) if overall_scores else 0.0,
        "pass_rate": round(pass_rate, 3),
        "mean_ground_truth_score": round(statistics.mean(ground_truth_scores), 3) if ground_truth_scores else 0.0,
        "mean_id_coverage_score": round(statistics.mean(id_coverage_scores), 3) if id_coverage_scores else 0.0,
        "id_requirement_pass_rate": round(id_requirement_pass_rate, 3),
    }

## Run the Evaluation

In [22]:
async def run_eval_case(case: dict) -> dict:
    try:
        output_text = await ask_simple_fraud_agent(case["prompt"], fresh_session=True)
        grades = item_level_deterministic_grader(case, output_text)
        result = {
            "id": case["id"],
            "prompt": case["prompt"],
            "expected_signals": ", ".join(case["expected_signals"]),
            "ground_truth_label_column": case.get("ground_truth_label_column"),
            "ground_truth_positive_count": case.get("ground_truth_positive_count"),
            "output": output_text,
            **grades,
        }
        return result
    except Exception as exc:
        print(f"Error running case {case['id']}: {exc}")
        raise

In [30]:
results = []
for case in eval_cases:
    print(f"Running {case['id']} ...")
    results.append(await run_eval_case(case))

/home/coder/eval-agents/.venv/lib/python3.12/site-packages/google/adk/runners.py:1481: DeprecationWarning: deprecated
  save_input_blobs_as_artifacts=run_config.save_input_blobs_as_artifacts,
2026-03-26 17:59:57,721 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 17:59:57,833 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False

Running fraud-001 ...

/home/coder/eval-agents/.venv/lib/python3.12/site-packages/google/genai/_api_client.py:755: DeprecationWarning: Inheritance class AiohttpClientSession from ClientSession is discouraged
  class AiohttpClientSession(aiohttp.ClientSession):  # type: ignore[misc]
2026-03-26 18:00:01,449 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:00:01,454 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:00:01,455 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:00:01,643 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:00:01,645 INFO e2b.api: Response 201
2026-03-26 18:00:01,647 INFO e2b.api.client_async: Request: POST https://49999-iqc3tm7i0olh76ojsurz5.e2b.app/execute
2026-03-26 18:00:01,779 INFO e2b.api.client_async: Response: 200 https://49999-iqc3tm7i0olh76ojsurz5.e2b.app/execute
2026-03-26 18:00:01,928 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/iqc3tm7i0olh76ojsurz5
2026-03-26 18:00:01,929 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/iqc3tm7i0olh76ojsurz5
2026-03-26 18:00:02,044 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/iqc3tm7i0olh76ojsurz5
2026-03-26 18:00:02,045 INFO e2b.api: Response 204
2026-03-26 18:00:02,054 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:00:02,169 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:00:05,062 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:00:05,068 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:00:05,069 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:00:05,266 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:00:05,267 INFO e2b.api: Response 201
2026-03-26 18:00:05,270 INFO e2b.api.client_async: Request: POST https://49999-ig0qvgxf850ejgvgbnrnh.e2b.app/execute
2026-03-26 18:00:05,411 INFO e2b.api.client_async: Response: 200 https://49999-ig0qvgxf850ejgvgbnrnh.e2b.app/execute
2026-03-26 18:00:05,574 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/ig0qvgxf850ejgvgbnrnh
2026-03-26 18:00:05,575 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/ig0qvgxf850ejgvgbnrnh
2026-03-26 18:00:05,690 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/ig0qvgxf850ejgvgbnrnh
2026-03-26 18:00:05,691 INFO e2b.api: Response 204
2026-03-26 18:00:05,697 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:00:05,814 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:00:10,218 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:00:10,226 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:00:10,227 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:00:10,446 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:00:10,447 INFO e2b.api: Response 201
2026-03-26 18:00:10,450 INFO e2b.api.client_async: Request: POST https://49999-i26agoeqxvsu4agxix4rr.e2b.app/execute
2026-03-26 18:00:10,592 INFO e2b.api.client_async: Response: 200 https://49999-i26agoeqxvsu4agxix4rr.e2b.app/execute
2026-03-26 18:00:14,175 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/i26agoeqxvsu4agxix4rr
2026-03-26 18:00:14,176 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/i26agoeqxvsu4agxix4rr
2026-03-26 18:00:14,285 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/i26agoeqxvsu4agxix4rr
2026-03-26 18:00:14,286 INFO e2b.api: Response 204
2026-03-26 18:00:14,294 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:00:14,402 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:00:17,379 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:00:17,386 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:00:17,387 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:00:17,547 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:00:17,548 INFO e2b.api: Response 201
2026-03-26 18:00:17,551 INFO e2b.api.client_async: Request: POST https://49999-iluorsar6stt6n73nlvsk.e2b.app/execute
2026-03-26 18:00:17,673 INFO e2b.api.client_async: Response: 200 https://49999-iluorsar6stt6n73nlvsk.e2b.app/execute
2026-03-26 18:00:18,912 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/iluorsar6stt6n73nlvsk
2026-03-26 18:00:18,913 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/iluorsar6stt6n73nlvsk
2026-03-26 18:00:19,029 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/iluorsar6stt6n73nlvsk
2026-03-26 18:00:19,031 INFO e2b.api: Response 204
2026-03-26 18:00:19,037 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:00:19,156 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:00:24,842 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:00:24,852 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:00:24,853 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:00:25,026 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:00:25,028 INFO e2b.api: Response 201
2026-03-26 18:00:25,031 INFO e2b.api.client_async: Request: POST https://49999-ip8mvcg1szbqojhygwx6p.e2b.app/execute
2026-03-26 18:00:25,151 INFO e2b.api.client_async: Response: 200 https://49999-ip8mvcg1szbqojhygwx6p.e2b.app/execute
2026-03-26 18:00:30,587 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/ip8mvcg1szbqojhygwx6p
2026-03-26 18:00:30,589 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/ip8mvcg1szbqojhygwx6p
2026-03-26 18:00:30,698 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/ip8mvcg1szbqojhygwx6p
2026-03-26 18:00:30,700 INFO e2b.api: Response 204
2026-03-26 18:00:30,708 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:00:30,824 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:00:36,873 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:00:36,881 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:00:36,882 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:00:37,203 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:00:37,205 INFO e2b.api: Response 201
2026-03-26 18:00:37,208 INFO e2b.api.client_async: Request: POST https://49999-iy4nb3thd39t8s199f7fx.e2b.app/execute
2026-03-26 18:00:37,347 INFO e2b.api.client_async: Response: 200 https://49999-iy4nb3thd39t8s199f7fx.e2b.app/execute
2026-03-26 18:00:43,035 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/iy4nb3thd39t8s199f7fx
2026-03-26 18:00:43,035 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/iy4nb3thd39t8s199f7fx
2026-03-26 18:00:43,151 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/iy4nb3thd39t8s199f7fx
2026-03-26 18:00:43,152 INFO e2b.api: Response 204
2026-03-26 18:00:43,159 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:00:43,273 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:00:46,241 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:00:46,250 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:00:46,250 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:00:46,512 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:00:46,513 INFO e2b.api: Response 201
2026-03-26 18:00:46,515 INFO e2b.api.client_async: Request: POST https://49999-iamf4tj00ly1lxruxs9p1.e2b.app/execute
2026-03-26 18:00:46,664 INFO e2b.api.client_async: Response: 200 https://49999-iamf4tj00ly1lxruxs9p1.e2b.app/execute
2026-03-26 18:00:50,621 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/iamf4tj00ly1lxruxs9p1
2026-03-26 18:00:50,622 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/iamf4tj00ly1lxruxs9p1
2026-03-26 18:00:50,732 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/iamf4tj00ly1lxruxs9p1
2026-03-26 18:00:50,734 INFO e2b.api: Response 204
2026-03-26 18:00:50,740 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:00:50,849 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:00:54,360 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:00:54,368 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:00:54,369 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:00:54,551 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:00:54,552 INFO e2b.api: Response 201
2026-03-26 18:00:54,554 INFO e2b.api.client_async: Request: POST https://49999-ikfwi7ucyvhx6f2nfga4e.e2b.app/execute
2026-03-26 18:00:54,678 INFO e2b.api.client_async: Response: 200 https://49999-ikfwi7ucyvhx6f2nfga4e.e2b.app/execute
2026-03-26 18:00:55,904 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/ikfwi7ucyvhx6f2nfga4e
2026-03-26 18:00:55,905 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/ikfwi7ucyvhx6f2nfga4e
2026-03-26 18:00:56,020 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/ikfwi7ucyvhx6f2nfga4e
2026-03-26 18:00:56,021 INFO e2b.api: Response 204
2026-03-26 18:00:56,028 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:00:56,145 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:01:18,613 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:01:18,622 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:01:18,623 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:01:18,788 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:01:18,789 INFO e2b.api: Response 201
2026-03-26 18:01:18,792 INFO e2b.api.client_async: Request: POST https://49999-iw06sij5fzs8osnkhpzz9.e2b.app/execute
2026-03-26 18:01:18,925 INFO e2b.api.client_async: Response: 200 https://49999-iw06sij5fzs8osnkhpzz9.e2b.app/execute
2026-03-26 18:01:20,266 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/iw06sij5fzs8osnkhpzz9
2026-03-26 18:01:20,267 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/iw06sij5fzs8osnkhpzz9
2026-03-26 18:01:20,379 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/iw06sij5fzs8osnkhpzz9
2026-03-26 18:01:20,380 INFO e2b.api: Response 204
2026-03-26 18:01:20,388 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:01:20,497 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:01:24,028 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:01:24,035 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:01:24,036 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:01:24,241 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:01:24,242 INFO e2b.api: Response 201
2026-03-26 18:01:24,245 INFO e2b.api.client_async: Request: POST https://49999-i8l67ic0kn4sjygx4hy1f.e2b.app/execute
2026-03-26 18:01:24,464 INFO e2b.api.client_async: Response: 200 https://49999-i8l67ic0kn4sjygx4hy1f.e2b.app/execute
2026-03-26 18:01:24,590 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/i8l67ic0kn4sjygx4hy1f
2026-03-26 18:01:24,590 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/i8l67ic0kn4sjygx4hy1f
2026-03-26 18:01:24,704 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/i8l67ic0kn4sjygx4hy1f
2026-03-26 18:01:24,705 INFO e2b.api: Response 204
2026-03-26 18:01:24,713 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:01:24,825 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:01:34,879 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:01:34,893 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:01:34,895 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:01:35,054 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:01:35,055 INFO e2b.api: Response 201
2026-03-26 18:01:35,058 INFO e2b.api.client_async: Request: POST https://49999-ia0csykewnx681bj7w6wf.e2b.app/execute
2026-03-26 18:01:35,180 INFO e2b.api.client_async: Response: 200 https://49999-ia0csykewnx681bj7w6wf.e2b.app/execute
2026-03-26 18:01:38,332 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/ia0csykewnx681bj7w6wf
2026-03-26 18:01:38,333 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/ia0csykewnx681bj7w6wf
2026-03-26 18:01:38,443 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/ia0csykewnx681bj7w6wf
2026-03-26 18:01:38,445 INFO e2b.api: Response 204
2026-03-26 18:01:38,452 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:01:38,562 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:01:50,135 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:01:50,143 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:01:50,144 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:01:50,505 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:01:50,506 INFO e2b.api: Response 201
2026-03-26 18:01:50,510 INFO e2b.api.client_async: Request: POST https://49999-if3njpkvakeendkx4o8iv.e2b.app/execute
2026-03-26 18:01:50,774 INFO e2b.api.client_async: Response: 200 https://49999-if3njpkvakeendkx4o8iv.e2b.app/execute
2026-03-26 18:01:51,171 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/if3njpkvakeendkx4o8iv
2026-03-26 18:01:51,172 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/if3njpkvakeendkx4o8iv
2026-03-26 18:01:51,312 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/if3njpkvakeendkx4o8iv
2026-03-26 18:01:51,313 INFO e2b.api: Response 204
2026-03-26 18:01:51,321 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:01:51,430 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:01:57,772 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:01:57,783 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:01:57,783 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:01:57,954 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:01:57,956 INFO e2b.api: Response 201
2026-03-26 18:01:57,958 INFO e2b.api.client_async: Request: POST https://49999-in41l18vyw0eepdcu8rzq.e2b.app/execute
2026-03-26 18:01:58,093 INFO e2b.api.client_async: Response: 200 https://49999-in41l18vyw0eepdcu8rzq.e2b.app/execute
2026-03-26 18:01:58,210 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/in41l18vyw0eepdcu8rzq
2026-03-26 18:01:58,210 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/in41l18vyw0eepdcu8rzq
2026-03-26 18:01:58,327 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/in41l18vyw0eepdcu8rzq
2026-03-26 18:01:58,329 INFO e2b.api: Response 204
2026-03-26 18:01:58,336 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:01:58,449 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:02:04,777 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:02:04,785 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:02:04,786 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:02:04,973 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:02:04,974 INFO e2b.api: Response 201
2026-03-26 18:02:04,977 INFO e2b.api.client_async: Request: POST https://49999-iutg7pmdbaw1k0kdvlfsu.e2b.app/execute
2026-03-26 18:02:05,114 INFO e2b.api.client_async: Response: 200 https://49999-iutg7pmdbaw1k0kdvlfsu.e2b.app/execute
2026-03-26 18:02:05,258 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/iutg7pmdbaw1k0kdvlfsu
2026-03-26 18:02:05,258 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/iutg7pmdbaw1k0kdvlfsu
2026-03-26 18:02:05,375 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/iutg7pmdbaw1k0kdvlfsu
2026-03-26 18:02:05,376 INFO e2b.api: Response 204
2026-03-26 18:02:05,384 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:02:05,497 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:02:12,401 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:02:12,411 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:02:12,412 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:02:12,575 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:02:12,576 INFO e2b.api: Response 201
2026-03-26 18:02:12,579 INFO e2b.api.client_async: Request: POST https://49999-im7pz89c12zocba2mnkag.e2b.app/execute
2026-03-26 18:02:12,713 INFO e2b.api.client_async: Response: 200 https://49999-im7pz89c12zocba2mnkag.e2b.app/execute
2026-03-26 18:02:12,833 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/im7pz89c12zocba2mnkag

Running fraud-002 ...

2026-03-26 18:02:44,707 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:02:44,713 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:02:44,714 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:02:44,873 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:02:44,874 INFO e2b.api: Response 201
2026-03-26 18:02:44,877 INFO e2b.api.client_async: Request: POST https://49999-ihl3lm1003sqv24fvv22p.e2b.app/execute
2026-03-26 18:02:45,003 INFO e2b.api.client_async: Response: 200 https://49999-ihl3lm1003sqv24fvv22p.e2b.app/execute
2026-03-26 18:02:45,117 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/ihl3lm1003sqv24fvv22p
2026-03-26 18:02:45,118 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/ihl3lm1003sqv24fvv22p
2026-03-26 18:02:45,234 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/ihl3lm1003sqv24fvv22p
2026-03-26 18:02:45,235 INFO e2b.api: Response 204
2026-03-26 18:02:45,241 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:02:45,350 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:02:57,717 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:02:57,725 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:02:57,726 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:02:57,885 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:02:57,886 INFO e2b.api: Response 201
2026-03-26 18:02:57,890 INFO e2b.api.client_async: Request: POST https://49999-ipz4z1g4t4073t2ub0b98.e2b.app/execute
2026-03-26 18:02:58,022 INFO e2b.api.client_async: Response: 200 https://49999-ipz4z1g4t4073t2ub0b98.e2b.app/execute
2026-03-26 18:03:01,991 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/ipz4z1g4t4073t2ub0b98
2026-03-26 18:03:01,991 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/ipz4z1g4t4073t2ub0b98
2026-03-26 18:03:02,109 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/ipz4z1g4t4073t2ub0b98
2026-03-26 18:03:02,110 INFO e2b.api: Response 204
2026-03-26 18:03:02,117 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:03:02,237 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:03:10,248 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:03:10,255 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:03:10,256 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:03:10,417 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:03:10,419 INFO e2b.api: Response 201
2026-03-26 18:03:10,422 INFO e2b.api.client_async: Request: POST https://49999-idqpwezls4xccywp94t9x.e2b.app/execute
2026-03-26 18:03:10,545 INFO e2b.api.client_async: Response: 200 https://49999-idqpwezls4xccywp94t9x.e2b.app/execute
2026-03-26 18:03:11,535 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/idqpwezls4xccywp94t9x
2026-03-26 18:03:11,536 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/idqpwezls4xccywp94t9x
2026-03-26 18:03:11,652 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/idqpwezls4xccywp94t9x
2026-03-26 18:03:11,654 INFO e2b.api: Response 204
2026-03-26 18:03:11,661 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:03:11,769 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:03:14,063 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:03:14,070 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:03:14,071 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:03:14,238 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:03:14,239 INFO e2b.api: Response 201
2026-03-26 18:03:14,243 INFO e2b.api.client_async: Request: POST https://49999-iyimzudzupl4q78wtb9rn.e2b.app/execute
2026-03-26 18:03:14,369 INFO e2b.api.client_async: Response: 200 https://49999-iyimzudzupl4q78wtb9rn.e2b.app/execute
2026-03-26 18:03:15,397 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/iyimzudzupl4q78wtb9rn
2026-03-26 18:03:15,398 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/iyimzudzupl4q78wtb9rn
2026-03-26 18:03:15,553 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/iyimzudzupl4q78wtb9rn
2026-03-26 18:03:15,555 INFO e2b.api: Response 204
2026-03-26 18:03:15,562 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:03:15,675 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:03:18,473 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:03:18,481 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:03:18,482 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:03:18,655 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:03:18,656 INFO e2b.api: Response 201
2026-03-26 18:03:18,659 INFO e2b.api.client_async: Request: POST https://49999-ij3273vzh06reco17xrex.e2b.app/execute
2026-03-26 18:03:18,773 INFO e2b.api.client_async: Response: 200 https://49999-ij3273vzh06reco17xrex.e2b.app/execute
2026-03-26 18:03:21,365 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/ij3273vzh06reco17xrex
2026-03-26 18:03:21,366 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/ij3273vzh06reco17xrex
2026-03-26 18:03:21,480 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/ij3273vzh06reco17xrex
2026-03-26 18:03:21,481 INFO e2b.api: Response 204
2026-03-26 18:03:21,489 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:03:21,600 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:03:27,994 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:03:28,001 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:03:28,002 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:03:28,165 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:03:28,166 INFO e2b.api: Response 201
2026-03-26 18:03:28,169 INFO e2b.api.client_async: Request: POST https://49999-ic4qux0zdrwl7iunju0kj.e2b.app/execute
2026-03-26 18:03:28,281 INFO e2b.api.client_async: Response: 200 https://49999-ic4qux0zdrwl7iunju0kj.e2b.app/execute
2026-03-26 18:03:28,384 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/ic4qux0zdrwl7iunju0kj
2026-03-26 18:03:28,385 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/ic4qux0zdrwl7iunju0kj
2026-03-26 18:03:28,506 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/ic4qux0zdrwl7iunju0kj
2026-03-26 18:03:28,508 INFO e2b.api: Response 204
2026-03-26 18:03:28,514 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:03:28,623 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:03:30,935 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:03:30,942 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:03:30,943 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:03:31,118 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:03:31,119 INFO e2b.api: Response 201
2026-03-26 18:03:31,122 INFO e2b.api.client_async: Request: POST https://49999-ixhau8e7mo8fiwtturhen.e2b.app/execute
2026-03-26 18:03:31,241 INFO e2b.api.client_async: Response: 200 https://49999-ixhau8e7mo8fiwtturhen.e2b.app/execute
2026-03-26 18:03:31,341 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/ixhau8e7mo8fiwtturhen
2026-03-26 18:03:31,342 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/ixhau8e7mo8fiwtturhen
2026-03-26 18:03:31,463 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/ixhau8e7mo8fiwtturhen
2026-03-26 18:03:31,464 INFO e2b.api: Response 204
2026-03-26 18:03:31,472 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:03:31,584 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:03:40,751 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:03:40,759 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:03:40,759 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:03:40,901 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:03:40,903 INFO e2b.api: Response 201
2026-03-26 18:03:40,905 INFO e2b.api.client_async: Request: POST https://49999-imqmhc8ojxdb806mau0cd.e2b.app/execute
2026-03-26 18:03:41,018 INFO e2b.api.client_async: Response: 200 https://49999-imqmhc8ojxdb806mau0cd.e2b.app/execute
2026-03-26 18:03:41,123 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/imqmhc8ojxdb806mau0cd
2026-03-26 18:03:41,124 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/imqmhc8ojxdb806mau0cd
2026-03-26 18:03:41,244 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/imqmhc8ojxdb806mau0cd
2026-03-26 18:03:41,245 INFO e2b.api: Response 204
2026-03-26 18:03:41,252 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:03:41,359 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:03:46,609 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:03:46,617 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:03:46,618 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:03:46,785 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:03:46,786 INFO e2b.api: Response 201
2026-03-26 18:03:46,790 INFO e2b.api.client_async: Request: POST https://49999-ir9tyl7ekg6hjg6pudhaf.e2b.app/execute
2026-03-26 18:03:46,913 INFO e2b.api.client_async: Response: 200 https://49999-ir9tyl7ekg6hjg6pudhaf.e2b.app/execute
2026-03-26 18:03:50,606 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/ir9tyl7ekg6hjg6pudhaf
2026-03-26 18:03:50,607 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/ir9tyl7ekg6hjg6pudhaf
2026-03-26 18:03:50,731 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/ir9tyl7ekg6hjg6pudhaf
2026-03-26 18:03:50,733 INFO e2b.api: Response 204
2026-03-26 18:03:50,742 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:03:50,856 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:04:10,816 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:04:10,829 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:04:10,939 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False

Running fraud-003 ...

2026-03-26 18:04:15,205 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:04:15,211 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:04:15,212 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:04:15,373 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:04:15,374 INFO e2b.api: Response 201
2026-03-26 18:04:15,377 INFO e2b.api.client_async: Request: POST https://49999-iwslxvppi24raloknkq3c.e2b.app/execute
2026-03-26 18:04:15,506 INFO e2b.api.client_async: Response: 200 https://49999-iwslxvppi24raloknkq3c.e2b.app/execute
2026-03-26 18:04:15,618 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/iwslxvppi24raloknkq3c
2026-03-26 18:04:15,619 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/iwslxvppi24raloknkq3c
2026-03-26 18:04:15,742 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/iwslxvppi24raloknkq3c
2026-03-26 18:04:15,744 INFO e2b.api: Response 204
2026-03-26 18:04:15,750 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:04:15,863 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:04:24,367 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:04:24,376 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:04:24,376 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:04:24,543 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:04:24,544 INFO e2b.api: Response 201
2026-03-26 18:04:24,548 INFO e2b.api.client_async: Request: POST https://49999-izlt2msd2m1s1dce48575.e2b.app/execute
2026-03-26 18:04:24,664 INFO e2b.api.client_async: Response: 200 https://49999-izlt2msd2m1s1dce48575.e2b.app/execute
2026-03-26 18:04:24,766 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/izlt2msd2m1s1dce48575
2026-03-26 18:04:24,767 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/izlt2msd2m1s1dce48575
2026-03-26 18:04:24,887 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/izlt2msd2m1s1dce48575
2026-03-26 18:04:24,889 INFO e2b.api: Response 204
2026-03-26 18:04:24,896 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:04:25,006 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:04:40,166 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:04:40,172 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:04:40,173 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:04:40,339 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:04:40,341 INFO e2b.api: Response 201
2026-03-26 18:04:40,343 INFO e2b.api.client_async: Request: POST https://49999-id3j0lrfv3shircc3q2gq.e2b.app/execute
2026-03-26 18:04:40,466 INFO e2b.api.client_async: Response: 200 https://49999-id3j0lrfv3shircc3q2gq.e2b.app/execute
2026-03-26 18:04:42,632 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/id3j0lrfv3shircc3q2gq
2026-03-26 18:04:42,633 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/id3j0lrfv3shircc3q2gq
2026-03-26 18:04:42,753 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/id3j0lrfv3shircc3q2gq
2026-03-26 18:04:42,755 INFO e2b.api: Response 204
2026-03-26 18:04:42,761 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:04:42,877 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:05:05,591 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:05:05,599 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:05:05,600 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:05:05,765 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:05:05,766 INFO e2b.api: Response 201
2026-03-26 18:05:05,768 INFO e2b.api.client_async: Request: POST https://49999-iqlw9dr33x8ddtft43qmg.e2b.app/execute
2026-03-26 18:05:05,890 INFO e2b.api.client_async: Response: 200 https://49999-iqlw9dr33x8ddtft43qmg.e2b.app/execute
2026-03-26 18:05:09,744 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/iqlw9dr33x8ddtft43qmg
2026-03-26 18:05:09,746 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/iqlw9dr33x8ddtft43qmg
2026-03-26 18:05:09,880 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/iqlw9dr33x8ddtft43qmg
2026-03-26 18:05:09,882 INFO e2b.api: Response 204
2026-03-26 18:05:09,888 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:05:10,003 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:05:13,091 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:05:13,097 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:05:13,098 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:05:13,270 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:05:13,271 INFO e2b.api: Response 201
2026-03-26 18:05:13,274 INFO e2b.api.client_async: Request: POST https://49999-i2ctj45q4z1iv50khv6in.e2b.app/execute
2026-03-26 18:05:13,404 INFO e2b.api.client_async: Response: 200 https://49999-i2ctj45q4z1iv50khv6in.e2b.app/execute
2026-03-26 18:05:13,513 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/i2ctj45q4z1iv50khv6in
2026-03-26 18:05:13,514 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/i2ctj45q4z1iv50khv6in
2026-03-26 18:05:13,629 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/i2ctj45q4z1iv50khv6in
2026-03-26 18:05:13,630 INFO e2b.api: Response 204
2026-03-26 18:05:13,636 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:05:13,750 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:05:17,122 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:05:17,129 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:05:17,130 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:05:17,300 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:05:17,302 INFO e2b.api: Response 201
2026-03-26 18:05:17,304 INFO e2b.api.client_async: Request: POST https://49999-iap03jk0y1j9ht1nkobrw.e2b.app/execute
2026-03-26 18:05:17,449 INFO e2b.api.client_async: Response: 200 https://49999-iap03jk0y1j9ht1nkobrw.e2b.app/execute
2026-03-26 18:05:18,988 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/iap03jk0y1j9ht1nkobrw
2026-03-26 18:05:18,989 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/iap03jk0y1j9ht1nkobrw
2026-03-26 18:05:19,103 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/iap03jk0y1j9ht1nkobrw
2026-03-26 18:05:19,104 INFO e2b.api: Response 204
2026-03-26 18:05:19,111 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:05:19,221 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:05:22,019 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:05:22,027 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:05:22,028 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:05:22,198 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:05:22,200 INFO e2b.api: Response 201
2026-03-26 18:05:22,203 INFO e2b.api.client_async: Request: POST https://49999-i8xxwb1cupj8hso09woyt.e2b.app/execute
2026-03-26 18:05:22,324 INFO e2b.api.client_async: Response: 200 https://49999-i8xxwb1cupj8hso09woyt.e2b.app/execute
2026-03-26 18:05:24,111 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/i8xxwb1cupj8hso09woyt
2026-03-26 18:05:24,112 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/i8xxwb1cupj8hso09woyt
2026-03-26 18:05:24,233 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/i8xxwb1cupj8hso09woyt
2026-03-26 18:05:24,235 INFO e2b.api: Response 204
2026-03-26 18:05:24,242 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:05:24,354 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:05:26,874 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:05:26,881 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:05:26,883 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:05:27,055 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:05:27,056 INFO e2b.api: Response 201
2026-03-26 18:05:27,059 INFO e2b.api.client_async: Request: POST https://49999-igq40fjd9bwtr98worjqb.e2b.app/execute
2026-03-26 18:05:27,188 INFO e2b.api.client_async: Response: 200 https://49999-igq40fjd9bwtr98worjqb.e2b.app/execute
2026-03-26 18:05:31,552 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/igq40fjd9bwtr98worjqb
2026-03-26 18:05:31,553 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/igq40fjd9bwtr98worjqb
2026-03-26 18:05:31,668 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/igq40fjd9bwtr98worjqb
2026-03-26 18:05:31,670 INFO e2b.api: Response 204
2026-03-26 18:05:31,677 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:05:31,790 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:05:35,691 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:05:35,700 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:05:35,701 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:05:35,878 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:05:35,880 INFO e2b.api: Response 201
2026-03-26 18:05:35,884 INFO e2b.api.client_async: Request: POST https://49999-ito39ndz7ozk6b5uhq9v9.e2b.app/execute
2026-03-26 18:05:36,043 INFO e2b.api.client_async: Response: 200 https://49999-ito39ndz7ozk6b5uhq9v9.e2b.app/execute
2026-03-26 18:05:40,604 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/ito39ndz7ozk6b5uhq9v9
2026-03-26 18:05:40,605 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/ito39ndz7ozk6b5uhq9v9
2026-03-26 18:05:40,726 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/ito39ndz7ozk6b5uhq9v9
2026-03-26 18:05:40,727 INFO e2b.api: Response 204
2026-03-26 18:05:40,735 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:05:40,846 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:05:44,948 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:05:44,956 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:05:44,957 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:05:45,139 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:05:45,140 INFO e2b.api: Response 201
2026-03-26 18:05:45,143 INFO e2b.api.client_async: Request: POST https://49999-io9emgzm7azy1c80yk0p3.e2b.app/execute
2026-03-26 18:05:45,284 INFO e2b.api.client_async: Response: 200 https://49999-io9emgzm7azy1c80yk0p3.e2b.app/execute
2026-03-26 18:05:48,257 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/io9emgzm7azy1c80yk0p3
2026-03-26 18:05:48,258 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/io9emgzm7azy1c80yk0p3
2026-03-26 18:05:48,378 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/io9emgzm7azy1c80yk0p3
2026-03-26 18:05:48,380 INFO e2b.api: Response 204
2026-03-26 18:05:48,388 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:05:48,497 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:05:52,073 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:05:52,081 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:05:52,082 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:05:52,232 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:05:52,233 INFO e2b.api: Response 201
2026-03-26 18:05:52,236 INFO e2b.api.client_async: Request: POST https://49999-ifvz0so831ryv12r4zh3s.e2b.app/execute
2026-03-26 18:05:52,373 INFO e2b.api.client_async: Response: 200 https://49999-ifvz0so831ryv12r4zh3s.e2b.app/execute
2026-03-26 18:05:53,794 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/ifvz0so831ryv12r4zh3s
2026-03-26 18:05:53,795 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/ifvz0so831ryv12r4zh3s
2026-03-26 18:05:53,912 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/ifvz0so831ryv12r4zh3s
2026-03-26 18:05:53,913 INFO e2b.api: Response 204
2026-03-26 18:05:53,920 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:05:54,030 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:05:57,350 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:05:57,360 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:05:57,361 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:05:57,514 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:05:57,515 INFO e2b.api: Response 201
2026-03-26 18:05:57,520 INFO e2b.api.client_async: Request: POST https://49999-imwj5hurd3644mxz45654.e2b.app/execute
2026-03-26 18:05:57,639 INFO e2b.api.client_async: Response: 200 https://49999-imwj5hurd3644mxz45654.e2b.app/execute
2026-03-26 18:06:00,992 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/imwj5hurd3644mxz45654
2026-03-26 18:06:00,992 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/imwj5hurd3644mxz45654
2026-03-26 18:06:01,113 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/imwj5hurd3644mxz45654
2026-03-26 18:06:01,114 INFO e2b.api: Response 204
2026-03-26 18:06:01,121 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:06:01,233 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:06:09,635 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:06:09,645 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:06:09,646 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:06:09,931 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:06:09,933 INFO e2b.api: Response 201
2026-03-26 18:06:09,935 INFO e2b.api.client_async: Request: POST https://49999-iwemrxpohznn39aob5idd.e2b.app/execute
2026-03-26 18:06:10,046 INFO e2b.api.client_async: Response: 200 https://49999-iwemrxpohznn39aob5idd.e2b.app/execute
2026-03-26 18:06:14,617 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/iwemrxpohznn39aob5idd
2026-03-26 18:06:14,618 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/iwemrxpohznn39aob5idd
2026-03-26 18:06:14,740 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/iwemrxpohznn39aob5idd
2026-03-26 18:06:14,741 INFO e2b.api: Response 204
2026-03-26 18:06:14,748 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:06:14,860 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:06:18,056 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:06:18,065 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:06:18,066 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:06:18,243 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:06:18,244 INFO e2b.api: Response 201
2026-03-26 18:06:18,247 INFO e2b.api.client_async: Request: POST https://49999-i30zn1uvk3s4em633qcnz.e2b.app/execute
2026-03-26 18:06:18,373 INFO e2b.api.client_async: Response: 200 https://49999-i30zn1uvk3s4em633qcnz.e2b.app/execute
2026-03-26 18:06:19,475 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/i30zn1uvk3s4em633qcnz
2026-03-26 18:06:19,476 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/i30zn1uvk3s4em633qcnz
2026-03-26 18:06:19,609 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/i30zn1uvk3s4em633qcnz
2026-03-26 18:06:19,610 INFO e2b.api: Response 204
2026-03-26 18:06:19,618 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:06:19,730 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:06:24,014 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:06:24,025 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:06:24,026 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:06:24,177 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:06:24,178 INFO e2b.api: Response 201
2026-03-26 18:06:24,180 INFO e2b.api.client_async: Request: POST https://49999-i0jtumgh04y3v97gzoa3k.e2b.app/execute
2026-03-26 18:06:24,304 INFO e2b.api.client_async: Response: 200 https://49999-i0jtumgh04y3v97gzoa3k.e2b.app/execute
2026-03-26 18:06:25,600 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/i0jtumgh04y3v97gzoa3k
2026-03-26 18:06:25,601 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/i0jtumgh04y3v97gzoa3k
2026-03-26 18:06:25,777 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/i0jtumgh04y3v97gzoa3k
2026-03-26 18:06:25,779 INFO e2b.api: Response 204

Running fraud-004 ...

2026-03-26 18:13:04,918 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:13:04,923 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:13:04,924 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:13:05,232 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:13:05,233 INFO e2b.api: Response 201
2026-03-26 18:13:05,236 INFO e2b.api.client_async: Request: POST https://49999-i6o0cklekoriqzcsisa1n.e2b.app/execute
2026-03-26 18:13:05,373 INFO e2b.api.client_async: Response: 200 https://49999-i6o0cklekoriqzcsisa1n.e2b.app/execute
2026-03-26 18:13:05,477 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/i6o0cklekoriqzcsisa1n
2026-03-26 18:13:05,478 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/i6o0cklekoriqzcsisa1n
2026-03-26 18:13:05,595 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/i6o0cklekoriqzcsisa1n
2026-03-26 18:13:05,596 INFO e2b.api: Response 204
2026-03-26 18:13:05,602 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:13:05,712 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:13:10,076 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:13:10,083 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:13:10,084 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:13:10,090 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:13:10,091 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:13:10,096 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:13:10,097 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:13:10,306 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:13:10,308 INFO e2b.api: Response 201
2026-03-26 18:13:10,311 INFO e2b.api.client_async: Request: POST https://49999-iyszurmfvrh21nw2e4lot.e2b.app/execute
2026-03-26 18:13:10,370 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:13:10,371 INFO e2b.api: Response 201
2026-03-26 18:13:10,375 INFO e2b.api.client_async: Request: POST https://49999-ieaza4f8z8470wep3pege.e2b.app/execute
2026-03-26 18:13:10,421 INFO e2b.api.client_async: Response: 200 https://49999-iyszurmfvrh21nw2e4lot.e2b.app/execute
2026-03-26 18:13:10,516 INFO e2b.api.client_async: Response: 200 https://49999-ieaza4f8z8470wep3pege.e2b.app/execute
2026-03-26 18:13:10,554 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:13:10,555 INFO e2b.api: Response 201
2026-03-26 18:13:10,558 INFO e2b.api.client_async: Request: POST https://49999-ivqi49jsx4u76whz22eq7.e2b.app/execute
2026-03-26 18:13:10,689 INFO e2b.api.client_async: Response: 200 https://49999-ivqi49jsx4u76whz22eq7.e2b.app/execute
2026-03-26 18:13:12,058 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/ieaza4f8z8470wep3pege
2026-03-26 18:13:12,059 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/ieaza4f8z8470wep3pege
2026-03-26 18:13:12,174 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/ieaza4f8z8470wep3pege
2026-03-26 18:13:12,175 INFO e2b.api: Response 204
2026-03-26 18:13:12,993 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/iyszurmfvrh21nw2e4lot
2026-03-26 18:13:12,994 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/iyszurmfvrh21nw2e4lot
2026-03-26 18:13:13,109 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/iyszurmfvrh21nw2e4lot
2026-03-26 18:13:13,111 INFO e2b.api: Response 204
2026-03-26 18:13:14,639 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/ivqi49jsx4u76whz22eq7
2026-03-26 18:13:14,640 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/ivqi49jsx4u76whz22eq7
2026-03-26 18:13:14,754 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/ivqi49jsx4u76whz22eq7
2026-03-26 18:13:14,756 INFO e2b.api: Response 204
2026-03-26 18:13:14,763 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:13:14,875 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:13:24,890 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:13:24,898 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:13:24,899 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:13:24,905 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:13:24,906 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:13:24,911 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:13:24,912 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:13:25,079 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:13:25,081 INFO e2b.api: Response 201
2026-03-26 18:13:25,084 INFO e2b.api.client_async: Request: POST https://49999-iy464k2s44kivo4ie7ivm.e2b.app/execute
2026-03-26 18:13:25,086 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:13:25,088 INFO e2b.api: Response 201
2026-03-26 18:13:25,092 INFO e2b.api.client_async: Request: POST https://49999-ib567t3n73ba7qhj3y0xo.e2b.app/execute
2026-03-26 18:13:25,094 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:13:25,095 INFO e2b.api: Response 201
2026-03-26 18:13:25,098 INFO e2b.api.client_async: Request: POST https://49999-ijkgl2aosm550dbrr4mb9.e2b.app/execute
2026-03-26 18:13:25,203 INFO e2b.api.client_async: Response: 200 https://49999-iy464k2s44kivo4ie7ivm.e2b.app/execute
2026-03-26 18:13:25,216 INFO e2b.api.client_async: Response: 200 https://49999-ib567t3n73ba7qhj3y0xo.e2b.app/execute
2026-03-26 18:13:25,218 INFO e2b.api.client_async: Response: 200 https://49999-ijkgl2aosm550dbrr4mb9.e2b.app/execute
2026-03-26 18:13:26,838 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/ib567t3n73ba7qhj3y0xo
2026-03-26 18:13:26,839 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/ib567t3n73ba7qhj3y0xo
2026-03-26 18:13:26,954 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/ib567t3n73ba7qhj3y0xo
2026-03-26 18:13:26,955 INFO e2b.api: Response 204
2026-03-26 18:13:29,067 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/ijkgl2aosm550dbrr4mb9
2026-03-26 18:13:29,068 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/ijkgl2aosm550dbrr4mb9
2026-03-26 18:13:29,072 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/iy464k2s44kivo4ie7ivm
2026-03-26 18:13:29,073 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/iy464k2s44kivo4ie7ivm
2026-03-26 18:13:29,192 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/ijkgl2aosm550dbrr4mb9
2026-03-26 18:13:29,193 INFO e2b.api: Response 204
2026-03-26 18:13:29,197 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/iy464k2s44kivo4ie7ivm
2026-03-26 18:13:29,198 INFO e2b.api: Response 204
2026-03-26 18:13:29,206 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:13:29,325 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:13:40,989 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:13:40,998 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:13:40,999 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:13:41,003 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:13:41,004 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:13:41,009 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:13:41,009 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:13:41,181 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:13:41,182 INFO e2b.api: Response 201
2026-03-26 18:13:41,186 INFO e2b.api.client_async: Request: POST https://49999-igjy9xkx7veamfp79vufx.e2b.app/execute
2026-03-26 18:13:41,199 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:13:41,201 INFO e2b.api: Response 201
2026-03-26 18:13:41,204 INFO e2b.api.client_async: Request: POST https://49999-iqwyjn2hqy8t2j46s7n3w.e2b.app/execute
2026-03-26 18:13:41,213 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:13:41,215 INFO e2b.api: Response 201
2026-03-26 18:13:41,218 INFO e2b.api.client_async: Request: POST https://49999-irubsxtyksqtbncphi3o9.e2b.app/execute
2026-03-26 18:13:41,309 INFO e2b.api.client_async: Response: 200 https://49999-igjy9xkx7veamfp79vufx.e2b.app/execute
2026-03-26 18:13:41,333 INFO e2b.api.client_async: Response: 200 https://49999-iqwyjn2hqy8t2j46s7n3w.e2b.app/execute
2026-03-26 18:13:41,343 INFO e2b.api.client_async: Response: 200 https://49999-irubsxtyksqtbncphi3o9.e2b.app/execute
2026-03-26 18:13:41,442 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/iqwyjn2hqy8t2j46s7n3w
2026-03-26 18:13:41,443 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/iqwyjn2hqy8t2j46s7n3w
2026-03-26 18:13:41,468 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/irubsxtyksqtbncphi3o9
2026-03-26 18:13:41,469 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/irubsxtyksqtbncphi3o9
2026-03-26 18:13:41,584 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/irubsxtyksqtbncphi3o9
2026-03-26 18:13:41,585 INFO e2b.api: Response 204
2026-03-26 18:13:41,628 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/iqwyjn2hqy8t2j46s7n3w
2026-03-26 18:13:41,629 INFO e2b.api: Response 204
2026-03-26 18:13:42,478 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/igjy9xkx7veamfp79vufx
2026-03-26 18:13:42,479 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/igjy9xkx7veamfp79vufx
2026-03-26 18:13:42,595 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/igjy9xkx7veamfp79vufx
2026-03-26 18:13:42,596 INFO e2b.api: Response 204
2026-03-26 18:13:42,605 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:13:42,715 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:13:50,699 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:13:50,708 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:13:50,709 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:13:50,881 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:13:50,882 INFO e2b.api: Response 201
2026-03-26 18:13:50,885 INFO e2b.api.client_async: Request: POST https://49999-i8web0qvzx3lh6oh79u2b.e2b.app/execute
2026-03-26 18:13:50,999 INFO e2b.api.client_async: Response: 200 https://49999-i8web0qvzx3lh6oh79u2b.e2b.app/execute
2026-03-26 18:13:52,457 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/i8web0qvzx3lh6oh79u2b
2026-03-26 18:13:52,458 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/i8web0qvzx3lh6oh79u2b
2026-03-26 18:13:52,573 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/i8web0qvzx3lh6oh79u2b
2026-03-26 18:13:52,574 INFO e2b.api: Response 204
2026-03-26 18:13:52,582 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:13:52,702 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:14:13,985 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:14:13,999 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:14:14,110 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False

Running fraud-005 ...

2026-03-26 18:14:17,138 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:14:17,144 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:14:17,144 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:14:18,322 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:14:18,323 INFO e2b.api: Response 201
2026-03-26 18:14:18,326 INFO e2b.api.client_async: Request: POST https://49999-i6tkt1xuau43zrdedq9up.e2b.app/execute
2026-03-26 18:14:18,436 INFO e2b.api.client_async: Response: 200 https://49999-i6tkt1xuau43zrdedq9up.e2b.app/execute
2026-03-26 18:14:18,531 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/i6tkt1xuau43zrdedq9up
2026-03-26 18:14:18,532 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/i6tkt1xuau43zrdedq9up
2026-03-26 18:14:33,945 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/i6tkt1xuau43zrdedq9up
2026-03-26 18:14:33,946 INFO e2b.api: Response 204
2026-03-26 18:14:33,952 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:14:34,063 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:14:38,812 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:14:38,820 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:14:38,821 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:14:38,826 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:14:38,827 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:14:38,833 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:14:38,834 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:14:38,978 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:14:38,979 INFO e2b.api: Response 201
2026-03-26 18:14:38,983 INFO e2b.api.client_async: Request: POST https://49999-i32nheey1fehgj0nauk4h.e2b.app/execute
2026-03-26 18:14:39,007 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:14:39,009 INFO e2b.api: Response 201
2026-03-26 18:14:39,013 INFO e2b.api.client_async: Request: POST https://49999-iqrm3mrgvmu495binomeh.e2b.app/execute
2026-03-26 18:14:39,016 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:14:39,017 INFO e2b.api: Response 201
2026-03-26 18:14:39,021 INFO e2b.api.client_async: Request: POST https://49999-iobtopeu8jbjcbvgfsevs.e2b.app/execute
2026-03-26 18:14:39,122 INFO e2b.api.client_async: Response: 200 https://49999-i32nheey1fehgj0nauk4h.e2b.app/execute
2026-03-26 18:14:39,142 INFO e2b.api.client_async: Response: 200 https://49999-iqrm3mrgvmu495binomeh.e2b.app/execute
2026-03-26 18:14:39,151 INFO e2b.api.client_async: Response: 200 https://49999-iobtopeu8jbjcbvgfsevs.e2b.app/execute
2026-03-26 18:14:40,390 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/iqrm3mrgvmu495binomeh
2026-03-26 18:14:40,391 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/iqrm3mrgvmu495binomeh
2026-03-26 18:14:40,514 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/iqrm3mrgvmu495binomeh
2026-03-26 18:14:40,515 INFO e2b.api: Response 204
2026-03-26 18:14:41,852 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/i32nheey1fehgj0nauk4h
2026-03-26 18:14:41,853 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/i32nheey1fehgj0nauk4h
2026-03-26 18:14:41,974 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/i32nheey1fehgj0nauk4h
2026-03-26 18:14:41,975 INFO e2b.api: Response 204
2026-03-26 18:14:42,811 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/iobtopeu8jbjcbvgfsevs
2026-03-26 18:14:42,811 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/iobtopeu8jbjcbvgfsevs
2026-03-26 18:14:42,934 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/iobtopeu8jbjcbvgfsevs
2026-03-26 18:14:42,936 INFO e2b.api: Response 204
2026-03-26 18:14:42,943 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:14:43,053 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:14:52,075 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:14:52,081 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:14:52,083 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:14:52,250 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:14:52,251 INFO e2b.api: Response 201
2026-03-26 18:14:52,254 INFO e2b.api.client_async: Request: POST https://49999-id6qdhr7qze3e3pqyspt1.e2b.app/execute
2026-03-26 18:14:52,372 INFO e2b.api.client_async: Response: 200 https://49999-id6qdhr7qze3e3pqyspt1.e2b.app/execute
2026-03-26 18:14:52,488 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/id6qdhr7qze3e3pqyspt1
2026-03-26 18:14:52,488 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/id6qdhr7qze3e3pqyspt1
2026-03-26 18:14:52,609 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/id6qdhr7qze3e3pqyspt1
2026-03-26 18:14:52,610 INFO e2b.api: Response 204
2026-03-26 18:14:52,618 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:14:52,728 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:15:01,438 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:15:01,446 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:15:01,447 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:15:01,628 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:15:01,629 INFO e2b.api: Response 201
2026-03-26 18:15:01,633 INFO e2b.api.client_async: Request: POST https://49999-i660malwygvro8t8i81uz.e2b.app/execute
2026-03-26 18:15:01,769 INFO e2b.api.client_async: Response: 200 https://49999-i660malwygvro8t8i81uz.e2b.app/execute
2026-03-26 18:15:06,849 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/i660malwygvro8t8i81uz
2026-03-26 18:15:06,849 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/i660malwygvro8t8i81uz
2026-03-26 18:15:06,970 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/i660malwygvro8t8i81uz
2026-03-26 18:15:06,971 INFO e2b.api: Response 204
2026-03-26 18:15:06,978 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:15:07,092 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:15:10,839 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:15:10,847 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:15:10,848 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:15:10,991 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:15:10,993 INFO e2b.api: Response 201
2026-03-26 18:15:10,996 INFO e2b.api.client_async: Request: POST https://49999-i9i0wdufdjmu749kpknar.e2b.app/execute
2026-03-26 18:15:11,124 INFO e2b.api.client_async: Response: 200 https://49999-i9i0wdufdjmu749kpknar.e2b.app/execute
2026-03-26 18:15:11,233 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/i9i0wdufdjmu749kpknar
2026-03-26 18:15:11,234 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/i9i0wdufdjmu749kpknar
2026-03-26 18:15:11,355 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/i9i0wdufdjmu749kpknar
2026-03-26 18:15:11,356 INFO e2b.api: Response 204
2026-03-26 18:15:11,363 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:15:11,476 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:15:17,118 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:15:17,126 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:15:17,127 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:15:17,299 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:15:17,300 INFO e2b.api: Response 201
2026-03-26 18:15:17,303 INFO e2b.api.client_async: Request: POST https://49999-ixgiit157hirz3czrbbkt.e2b.app/execute
2026-03-26 18:15:17,523 INFO e2b.api.client_async: Response: 200 https://49999-ixgiit157hirz3czrbbkt.e2b.app/execute
2026-03-26 18:15:18,724 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/ixgiit157hirz3czrbbkt
2026-03-26 18:15:18,724 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/ixgiit157hirz3czrbbkt
2026-03-26 18:15:18,846 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/ixgiit157hirz3czrbbkt
2026-03-26 18:15:18,847 INFO e2b.api: Response 204
2026-03-26 18:15:18,855 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:15:18,969 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:15:22,981 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:15:22,990 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:15:22,991 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:15:23,283 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:15:23,284 INFO e2b.api: Response 201
2026-03-26 18:15:23,287 INFO e2b.api.client_async: Request: POST https://49999-iea6ew5o7cmb2mj5qyi5a.e2b.app/execute
2026-03-26 18:15:23,514 INFO e2b.api.client_async: Response: 200 https://49999-iea6ew5o7cmb2mj5qyi5a.e2b.app/execute
2026-03-26 18:15:23,635 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/iea6ew5o7cmb2mj5qyi5a
2026-03-26 18:15:23,636 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/iea6ew5o7cmb2mj5qyi5a
2026-03-26 18:15:23,818 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/iea6ew5o7cmb2mj5qyi5a
2026-03-26 18:15:23,819 INFO e2b.api: Response 204
2026-03-26 18:15:23,826 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:15:23,940 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:15:27,128 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:15:27,137 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:15:27,138 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:15:27,300 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:15:27,301 INFO e2b.api: Response 201
2026-03-26 18:15:27,304 INFO e2b.api.client_async: Request: POST https://49999-inqthzienay25nwcjjw81.e2b.app/execute
2026-03-26 18:15:27,430 INFO e2b.api.client_async: Response: 200 https://49999-inqthzienay25nwcjjw81.e2b.app/execute
2026-03-26 18:15:27,540 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/inqthzienay25nwcjjw81
2026-03-26 18:15:27,541 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/inqthzienay25nwcjjw81
2026-03-26 18:15:27,661 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/inqthzienay25nwcjjw81
2026-03-26 18:15:27,662 INFO e2b.api: Response 204
2026-03-26 18:15:27,671 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:15:27,782 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:15:36,071 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:15:36,080 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:15:36,082 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:15:36,303 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:15:36,304 INFO e2b.api: Response 201
2026-03-26 18:15:36,308 INFO e2b.api.client_async: Request: POST https://49999-iaq3s2ptbasrhgk10975p.e2b.app/execute
2026-03-26 18:15:36,420 INFO e2b.api.client_async: Response: 200 https://49999-iaq3s2ptbasrhgk10975p.e2b.app/execute
2026-03-26 18:15:37,455 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/iaq3s2ptbasrhgk10975p
2026-03-26 18:15:37,456 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/iaq3s2ptbasrhgk10975p
2026-03-26 18:15:37,579 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/iaq3s2ptbasrhgk10975p
2026-03-26 18:15:37,580 INFO e2b.api: Response 204
2026-03-26 18:15:37,588 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:15:37,700 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:15:40,709 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:15:40,718 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:15:40,720 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:15:40,903 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:15:40,904 INFO e2b.api: Response 201
2026-03-26 18:15:40,908 INFO e2b.api.client_async: Request: POST https://49999-idxxicj6b4y0hi1k8js21.e2b.app/execute
2026-03-26 18:15:41,030 INFO e2b.api.client_async: Response: 200 https://49999-idxxicj6b4y0hi1k8js21.e2b.app/execute
2026-03-26 18:15:41,149 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/idxxicj6b4y0hi1k8js21
2026-03-26 18:15:41,150 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/idxxicj6b4y0hi1k8js21
2026-03-26 18:15:41,272 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/idxxicj6b4y0hi1k8js21
2026-03-26 18:15:41,273 INFO e2b.api: Response 204
2026-03-26 18:15:41,282 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:15:41,394 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:15:45,801 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:15:45,810 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:15:45,811 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:15:45,976 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:15:45,977 INFO e2b.api: Response 201
2026-03-26 18:15:45,980 INFO e2b.api.client_async: Request: POST https://49999-iy38zlt92qgut7t6qtngl.e2b.app/execute
2026-03-26 18:15:46,099 INFO e2b.api.client_async: Response: 200 https://49999-iy38zlt92qgut7t6qtngl.e2b.app/execute
2026-03-26 18:15:46,199 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/iy38zlt92qgut7t6qtngl
2026-03-26 18:15:46,200 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/iy38zlt92qgut7t6qtngl
2026-03-26 18:15:46,319 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/iy38zlt92qgut7t6qtngl
2026-03-26 18:15:46,320 INFO e2b.api: Response 204
2026-03-26 18:15:46,329 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:15:46,444 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:15:52,223 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:15:52,233 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:15:52,234 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:15:52,480 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:15:52,481 INFO e2b.api: Response 201
2026-03-26 18:15:52,485 INFO e2b.api.client_async: Request: POST https://49999-i4w8ggdquilq211lg9em7.e2b.app/execute
2026-03-26 18:15:52,605 INFO e2b.api.client_async: Response: 200 https://49999-i4w8ggdquilq211lg9em7.e2b.app/execute
2026-03-26 18:15:53,839 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/i4w8ggdquilq211lg9em7
2026-03-26 18:15:53,840 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/i4w8ggdquilq211lg9em7
2026-03-26 18:15:53,968 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/i4w8ggdquilq211lg9em7
2026-03-26 18:15:53,969 INFO e2b.api: Response 204
2026-03-26 18:15:53,978 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:15:54,093 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:15:58,972 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:15:58,981 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:15:58,982 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:15:59,154 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:15:59,155 INFO e2b.api: Response 201
2026-03-26 18:15:59,159 INFO e2b.api.client_async: Request: POST https://49999-ikrruo9km4pb1rkly7q13.e2b.app/execute
2026-03-26 18:15:59,294 INFO e2b.api.client_async: Response: 200 https://49999-ikrruo9km4pb1rkly7q13.e2b.app/execute
2026-03-26 18:15:59,428 INFO e2b.api: Request DELETE https://api.e2b.app/sandboxes/ikrruo9km4pb1rkly7q13
2026-03-26 18:15:59,429 INFO e2b.api.client_async: Request: DELETE https://api.e2b.app/sandboxes/ikrruo9km4pb1rkly7q13
2026-03-26 18:15:59,544 INFO e2b.api.client_async: Response: 204 https://api.e2b.app/sandboxes/ikrruo9km4pb1rkly7q13
2026-03-26 18:15:59,545 INFO e2b.api: Response 204
2026-03-26 18:15:59,553 WARNING google_genai._api_client: Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.
2026-03-26 18:15:59,664 INFO google_adk.google.adk.models.google_llm: Sending out request, model: gemini-3-pro-preview, backend: GoogleLLMVariant.GEMINI_API, stream: False
2026-03-26 18:16:03,482 INFO google_adk.google.adk.models.google_llm: Response received from the model.
2026-03-26 18:16:03,493 INFO e2b.api: Request POST https://api.e2b.app/sandboxes
2026-03-26 18:16:03,494 INFO e2b.api.client_async: Request: POST https://api.e2b.app/sandboxes
2026-03-26 18:16:03,661 INFO e2b.api.client_async: Response: 201 https://api.e2b.app/sandboxes
2026-03-26 18:16:03,663 INFO e2b.api: Response 201

In [32]:
results_df = pd.DataFrame(results)
results_df[
    [
        "id",
        "structure_score",
        "signals_score",
        "evidence_score",
        "id_coverage_score",
        "predicted_transaction_id_count",
        "meets_min_transaction_ids",
        "ground_truth_score",
        "overall_score",
        "pass",
    ]
]

,id,structure_score,signals_score,evidence_score,id_coverage_score,predicted_transaction_id_count,meets_min_transaction_ids,ground_truth_score,overall_score,pass
0,fraud-001,1.0,1.0,0.75,0.0,0,False,0.0,0.55,False
1,fraud-002,1.0,1.0,1.00,0.0,0,False,0.0,0.60,False
2,fraud-003,1.0,1.0,0.75,0.0,0,False,0.0,0.55,False
3,fraud-004,1.0,1.0,1.00,0.0,0,False,0.0,0.60,False
4,fraud-005,1.0,1.0,1.00,1.0,4,True,0.0,0.80,True

## Aggregate Metrics and Failure Analysis

In [33]:
run_metrics = run_level_grader(results)
run_metrics_df = pd.DataFrame([run_metrics])
run_metrics_df

,cases,mean_overall_score,min_overall_score,max_overall_score,pass_rate,mean_ground_truth_score,mean_id_coverage_score,id_requirement_pass_rate
0,5,0.62,0.55,0.8,0.2,0.0,0.2,0.2

In [34]:
failed_cases_df = results_df.loc[~results_df["pass"], ["id", "prompt", "overall_score", "output"]]
failed_cases_df if not failed_cases_df.empty else pd.DataFrame([{"status": "All cases passed"}])

,id,prompt,overall_score,output
0,fraud-001,Identify the top 3 highest-risk clients in the...,0.55,ANALYSIS:\nBy querying the database to aggrega...
1,fraud-002,Find merchants that appear in more than one fr...,0.60,ANALYSIS:\nWe have identified multiple merchan...
2,fraud-003,Compare the risk profile of high-velocity clie...,0.55,ANALYSIS:\nA rigorous comparison between High-...
3,fraud-004,Write a fraud investigation brief covering all...,0.60,ANALYSIS:\nA comprehensive multi-signal fraud ...

## LLM-as-Judge Evaluation

While the deterministic graders check for keyword presence and structure, an LLM judge can assess deeper qualities like reasoning coherence, evidence quality, and whether recommendations are actionable.

`create_llm_as_judge_evaluator` returns an async evaluator backed by an OpenAI model. A custom rubric focuses scoring on fraud-relevant criteria.

In [27]:
from aieng.agent_evals.evaluation.graders import create_llm_as_judge_evaluator
from aieng.agent_evals.evaluation.graders.config import LLMRequestConfig

fraud_rubric = """
1. **signal_coverage** — Score 1 only if the output explicitly addresses ALL fraud signals mentioned in the input prompt \
(e.g. if the prompt asks about both high-value amounts AND velocity, both must be covered with specific findings). \
Score 0 if any requested signal is missing or only mentioned in passing without supporting detail.

2. **evidence_quality** — Score 1 only if the output cites at least 3 concrete data points \
(e.g. specific transaction amounts, client IDs, merchant names, counts, or dollar thresholds). \
Vague language like "high transaction counts" or "large amounts" without actual values does NOT count. \
Score 0 if fewer than 3 concrete data points are cited or if claims are stated without supporting figures.

3. **transaction_id_citation** — Score 1 only if the output includes at least 3 specific transaction IDs \
(e.g., "transaction_id: 12345, 12346, 12347"). Generic references to "transaction IDs" without listing actual numeric IDs do NOT qualify. \
Score 0 if fewer than 3 concrete transaction IDs are cited.

4. **actionability** — Score 1 only if the output includes at least 2 distinct, specific recommendations \
(e.g. "escalate client X for manual review", "flag merchant Y", "set alert threshold at $Z"). \
Generic phrases like "monitor activity" or "review transactions" without identifying a specific entity or threshold do NOT qualify. \
Score 0 if recommendations are absent, generic, or fewer than 2.

5. **reasoning_quality** — Score 1 only if the output explains WHY each finding is suspicious \
(e.g. links amounts to a threshold, compares against a baseline, or identifies a pattern). \
Score 0 if the output only lists findings without any causal or comparative reasoning.

6. **ground_truth_transaction_id_alignment** — Use `expected_output.ground_truth_positive_transaction_ids_sample` as the reference set. \
Score 1 only if at least 2 transaction IDs cited in the response are present in that ground-truth sample. \
Score 0 if fewer than 2 cited IDs match the ground-truth sample, or if no transaction IDs are cited.
"""

fraud_judge = create_llm_as_judge_evaluator(
    name="fraud_judge",
    rubric_markdown=fraud_rubric,
    model_config=LLMRequestConfig(temperature=0.0),
)

print("LLM judge created.")

LLM judge created.

In [35]:
async def run_llm_judge_case(case: dict, output_text: str) -> dict:
    """Run the LLM judge for a single eval case and return scores as a flat dict."""
    llm_evals = await fraud_judge(
        input={"prompt": case["prompt"]},
        output={"response": output_text},
        expected_output={
            "expected_signals": case["expected_signals"],
            "ground_truth_positive_transaction_ids_sample": case.get(
                "ground_truth_positive_transaction_ids_sample", []
            ),
            "ground_truth_positive_count": case.get("ground_truth_positive_count", 0),
        },
        metadata={"case_id": case["id"]},
    )
    return {e.name: e.value for e in llm_evals}


case_by_id = {case["id"]: case for case in eval_cases}

llm_results = []
for row in results:
    print(f"Judging {row['id']} ...")
    case_ref = case_by_id[row["id"]]
    llm_case = {
        "id": case_ref["id"],
        "prompt": case_ref["prompt"],
        "expected_signals": case_ref["expected_signals"],
        "ground_truth_positive_transaction_ids_sample": case_ref.get(
            "ground_truth_positive_transaction_ids", []
        )[:200],
        "ground_truth_positive_count": case_ref.get("ground_truth_positive_count", 0),
    }
    llm_scores = await run_llm_judge_case(case=llm_case, output_text=row["output"])
    llm_results.append({"id": row["id"], **llm_scores})

llm_results_df = pd.DataFrame(llm_results)
llm_results_df

Judging fraud-001 ...
Judging fraud-002 ...
Judging fraud-003 ...
Judging fraud-004 ...
Judging fraud-005 ...

,id,signal_coverage,evidence_quality,transaction_id_citation,actionability,reasoning_quality,ground_truth_transaction_id_alignment
0,fraud-001,1,1,1,1,1,0
1,fraud-002,1,1,1,1,1,0
2,fraud-003,1,1,1,1,1,0
3,fraud-004,1,1,1,1,1,0
4,fraud-005,1,1,1,1,1,0

In [36]:
# Merge LLM judge scores with deterministic scores for a side-by-side comparison
combined_df = results_df[["id", "structure_score", "signals_score", "evidence_score", "overall_score", "id_coverage_score", "pass"]].merge(
    llm_results_df, on="id"
)
combined_df

,id,structure_score,signals_score,evidence_score,overall_score,id_coverage_score,pass,signal_coverage,evidence_quality,transaction_id_citation,actionability,reasoning_quality,ground_truth_transaction_id_alignment
0,fraud-001,1.0,1.0,0.75,0.55,0.0,False,1,1,1,1,1,0
1,fraud-002,1.0,1.0,1.00,0.60,0.0,False,1,1,1,1,1,0
2,fraud-003,1.0,1.0,0.75,0.55,0.0,False,1,1,1,1,1,0
3,fraud-004,1.0,1.0,1.00,0.60,0.0,False,1,1,1,1,1,0
4,fraud-005,1.0,1.0,1.00,0.80,1.0,True,1,1,1,1,1,0